config/routes.rb
Rails.application.routes.draw do
  get 'experiments/page1'

  get 'experiments/page2'

  get 'experiments/page3'

  get 'pages/batman'
  get 'pages/superman'
  get 'pages/batman_vs_superman'
  root 'pages#batman_vs_superman'
  post 'pages/saver_vote'

end

app/models/voto.rb
class Voto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  def page1
  end

  def page2
  end

  def page3
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def batman
  end
  def superman
  end
  def batman_vs_superman
  end
  def save_vote
  	@heroe=params[:txt_heroe]
  	@email=params[:txt_mail]

  	@newuser= User.new(heroe: @heroe, email: @email)

	if @newuser.save
		@respuesta = "Tu voto a sido registrado"
	else
		@respuesta = "Ocurrio un error"
	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/experiments/page1.html.erb
<h1>Experiments#page1</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore sequi accusantium laborum eum ea blanditiis distinctio error ad perspiciatis qui, at animi, quasi in veniam laboriosam, dolores eligendi fuga magnam.
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe tempore neque, consectetur dignissimos ratione cum modi, consequuntur magni at eum! Soluta eos quam libero dicta ea obcaecati quo cupiditate ipsam.</p>

app/views/experiments/page2.html.erb
<h1>Experiments#page2</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore sequi accusantium laborum eum ea blanditiis distinctio error ad perspiciatis qui, at animi, quasi in veniam laboriosam, dolores eligendi fuga magnam.
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe tempore neque, consectetur dignissimos ratione cum modi, consequuntur magni at eum! Soluta eos quam libero dicta ea obcaecati quo cupiditate ipsam.</p>

app/views/experiments/page3.html.erb
<h1>Experiments#page3</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore sequi accusantium laborum eum ea blanditiis distinctio error ad perspiciatis qui, at animi, quasi in veniam laboriosam, dolores eligendi fuga magnam.
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe tempore neque, consectetur dignissimos ratione cum modi, consequuntur magni at eum! Soluta eos quam libero dicta ea obcaecati quo cupiditate ipsam.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superheroes</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>	
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superheroes</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>	
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/batman.html.erb
<div class="row">
	<div class="col-md-12">
		<h1 style="color: white;">This looks like a job for Superman</h1>
	</div>
</div>

<script>
	$.backstretch(["<%= asset_path 'batman.jpg' %>"]);
</script>

app/views/pages/batman_vs_superman.html.erb
<div class="row">
  <div class="col-md-6 vs_batman">
  	<div class="contenido_form">
	  	<a href="<%= pages_batman_path %>" class="btn btn-primary btn-lg active bt_shero" role="button">Batman</a>
		<form action="<%= pages_saver_vote_path %>" method="post">
		<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
			<div class="form-group">
				<label for="txt_heroe">Heroe</label>
				<input name="txt_heroe" type="text" class="form-control" id="txt_nombre" placeholder="Batman">
			</div>
			<div class="form-group">
				<label for="txt_mail">Email</label>
				<input name="txt_mail" type="email" class="form-control" id="txt_mail" placeholder="juanito@hola.cl">
			</div>
			<button type="submit" class="btn btn-default">Votar</button>
		</form>
	</div>
  </div>
  <div class="col-md-6 vs_superman">
  	<div class="contenido_form">
	  	<a href="<%= pages_saver_vote_path %>" class="btn btn-primary btn-lg active bt_shero" role="button">Superman</a>
		<form action="<%= pages_superman_path %>" method="post">
		<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
			<div class="form-group">
				<label for="txt_heroe">Heroe</label>
				<input name="txt_heroe" type="text" class="form-control" id="txt_nombre" placeholder="Superman">
			</div>
			<div class="form-group">
				<label for="txt_mail">Email</label>
				<input name="txt_mail" type="email" class="form-control" id="txt_mail" placeholder="juanito@hola.cl">
			</div>
			<button type="submit" class="btn btn-default">Votar</button>
		</form>
	</div>
  </div>
</div>

app/views/pages/saver_vote.html.erb
<p><%= @respuesta %></p>

app/views/pages/superman.html.erb
<div class="row">
	<div class="col-md-12">
		<h1 style="color: white;">This looks like a job for Superman</h1>
	</div>
</div>

<script>
	$.backstretch(["<%= asset_path 'sm.jpg' %>"]);
</script>